server:
  port: 8887

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
 
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: ms-platos
        uri: lb://MS-PLATOS
        predicates:
        - Path=/ms-platos/**
        
      - id: ms-ordenes
        uri: lb://MS-ORDENES
        predicates:
        - Path=/ms-ordenes/**
        
      - id: ms-personal
        uri: lb://MS-PERSONAL
        predicates:
        - Path=/ms-personal/**
        
      - id: ms-clientes
        uri: lb://MS-CLIENTES
        predicates:
        - Path=/ms-clientes/**
      
      - id: ms-opiniones
        uri: lb://MS-OPINIONES
        predicates:
        - Path=/ms-opiniones/**       
        
      - id: albums
        uri: https://jsonplaceholder.typicode.com/albums
        predicates:
        - Path=/albums       

management:
   endpoint:
     gateway:
       enabled: true
   endpoints:
     web:
       exposure:
         include: "gateway"