server:
  port: 8086
  servlet:
    context-path: /ms-platos
    
  error:
    include-details: always

# Configuraciones de la web          
  mvc:
    view:
      prefix: resources/templates
      suffix: html
               
# Conexión a MySQL

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mugiwara
    username: postgres
    password: 542345
    driver-class-name: org.postgresql.Driver
    
#Configuraciones JPA - Hibernate

jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
  hibernate:
    naming:
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka